#pragma once



#include "../framework.h"
#include "../Typedef.h"

const ULONGLONG U_GAME_UPDATELATE = 16u;

enum GAMEOBJECT_RENDER_TYPE
{
	GAMEOBJ_RENDER_UNKNOWN,

	GAMEOBJ_RENDER_SPRITE,
	GAMEOBJ_RENDER_TILEMAP,

	GAMEOBJ_RENDER_COUNT,
};

enum GAME_INPUT_TYPE
{
	GAME_INPUT_UNKNOWN,

	GAME_INPUT_UP,
	GAME_INPUT_LEFT,
	GAME_INPUT_DOWN,
	GAME_INPUT_RIGHT,

	GAME_INPUT_DODGE,

	GAME_INPUT_MAIN_ACTION,
	GAME_INPUT_SUB_ACTION,
	GAME_INPUT_CANCEL,

	GAME_SYS_CLICK_DOWN,
	GAME_SYS_CLICK_UP,
	GAME_SYS_MENU,

	GAME_INPUT_NUM,
};